Repository quarx-ui/quarx, pull requests merged in 2022-11, with the labels that each got.

#99 fix(Tabs): Погрешность при округлении ширины элементов в Chrome
  packages/core/src/styled/Tabs/common/useTabs.ts
Labels: bug

#105 fix(new_script): Исправлен баг с SingleLine импортом Props в ComponentsProps
  packages/core/styles/engine/theme/createTheme/types.ts
  scripts/cli/src/components.ts
Labels: bug

#101 feat: Добавлены компоненты If, Switch
  packages/core/src/index.ts
  packages/core/src/unstyled/If/If.tsx
  packages/core/src/unstyled/If/__tests__/If.test.tsx
  packages/core/src/unstyled/If/index.ts
  packages/core/src/unstyled/If/stories/If.story.tsx
  packages/core/src/unstyled/If/types.ts
  packages/core/src/unstyled/Switch/Case/Case.tsx
  packages/core/src/unstyled/Switch/Case/index.ts
  packages/core/src/unstyled/Switch/Case/types.ts
  packages/core/src/unstyled/Switch/Switch.tsx
  packages/core/src/unstyled/Switch/__tests__/Switch.test.tsx
  packages/core/src/unstyled/Switch/index.ts
  packages/core/src/unstyled/Switch/stories/Switch.story.tsx
  packages/core/src/unstyled/Switch/types.ts
Labels: enhancement

#100 feat: Добавлен компонент ClickAwayListener
  packages/core/index.ts
  packages/core/package.json
  packages/core/polyfills.ts
  packages/core/src/index.ts
  packages/core/src/unstyled/ClickAwayListener/ClickAwayListener.tsx
  packages/core/src/unstyled/ClickAwayListener/__tests__/ClickAwayListener.test.tsx
  packages/core/src/unstyled/ClickAwayListener/constants.ts
  packages/core/src/unstyled/ClickAwayListener/index.ts
  packages/core/src/unstyled/ClickAwayListener/stories/ClickAwayListener.story.tsx
  packages/core/src/unstyled/ClickAwayListener/types.ts
  packages/core/utils/clickedRootScrollbar.ts
  packages/core/utils/index.ts
  packages/core/utils/makeEventFromSyntheticEvent.ts
  packages/core/utils/ownerDocument.ts
  packages/core/utils/polyfills/events/composedPath.ts
  packages/core/utils/polyfills/events/index.ts
  packages/core/utils/polyfills/index.ts
Labels: enhancement

#92 feat: Добавлен компонент Chips
  packages/core/src/index.ts
  packages/core/src/styled/Chips/Chips.tsx
  packages/core/src/styled/Chips/__tests__/Chips.test.tsx
  packages/core/src/styled/Chips/__tests__/__snapshots__/Chips.test.tsx.snap
  packages/core/src/styled/Chips/assets/index.ts
  packages/core/src/styled/Chips/assets/medium/checkmarkIcon.svg
  packages/core/src/styled/Chips/assets/medium/closeIcon.svg
  packages/core/src/styled/Chips/assets/medium/triangleIcon.svg
  packages/core/src/styled/Chips/assets/small/checkmarkIcon.svg
  packages/core/src/styled/Chips/assets/small/closeIcon.svg
  packages/core/src/styled/Chips/assets/small/triangleIcon.svg
  packages/core/src/styled/Chips/constants.ts
  packages/core/src/styled/Chips/index.ts
  packages/core/src/styled/Chips/stories/Chips.story.tsx
  packages/core/src/styled/Chips/styles/index.ts
  packages/core/src/styled/Chips/styles/types.ts
  packages/core/src/styled/Chips/styles/vars.ts
  packages/core/src/styled/Chips/types.ts
  packages/core/styles/engine/theme/createTheme/types.ts
  packages/core/utils/hooks/index.ts
  packages/core/utils/hooks/useBooleanState/index.ts
  packages/core/utils/hooks/useBooleanState/useBooleanState.ts
  packages/core/utils/hooks/useId/index.ts
  packages/core/utils/hooks/useId/useId.ts
Labels: enhancement

#129 docs: Обновлены соглашения по коммитам
  md/conventions/commit.md
Labels: documentation
