Repository quarx-ui/quarx, pull requests merged in 2022-08, with the labels that each got.

#46 feat: #20 - Добавлен компонент **TextField**
  packages/core/package.json
  packages/core/src/TextField/BaseTextField.tsx
  packages/core/src/TextField/TextField.tsx
  packages/core/src/TextField/assets/AttentionSmall.svg
  packages/core/src/TextField/assets/cross.svg
  packages/core/src/TextField/assets/index.ts
  packages/core/src/TextField/elements/Bottom.tsx
  packages/core/src/TextField/elements/Label.tsx
  packages/core/src/TextField/elements/RightItem.tsx
  packages/core/src/TextField/elements/index.ts
  packages/core/src/TextField/elements/types.ts
  packages/core/src/TextField/index.ts
  packages/core/src/TextField/stories/TextField.story.tsx
  packages/core/src/TextField/stories/assets/AttentionSmall.svg
  packages/core/src/TextField/stories/assets/ChevronMedium.svg
  packages/core/src/TextField/stories/assets/CrossCircleMedium.svg
  packages/core/src/TextField/stories/assets/UserMedium.svg
  packages/core/src/TextField/stories/assets/index.ts
  packages/core/src/TextField/stories/descriptions.ts
  packages/core/src/TextField/styles/index.ts
  packages/core/src/TextField/styles/types.ts
  packages/core/src/TextField/types.ts
  packages/core/src/index.ts
  packages/core/storybook/DisplayVariants/DisplayVariants.tsx
  packages/core/storybook/DisplayVariants/index.ts
  packages/core/storybook/docsPage.tsx
  packages/core/styles/engine/theme/createTheme/types.ts
  packages/core/utils/mergeRefs.ts
  yarn.lock
Labels: enhancement

#61 fix(makeStyles): Исправлена типизация makeStyles, удалены лишние пров…
  packages/core/styles/engine/makeStyles/makeStyles.ts
  packages/core/styles/engine/types.ts
Labels: bug

#60 fix(elevations): Удалено дублирование объектов с размерами
  packages/core/styles/engine/theme/elevations/createElevations.ts
  packages/core/styles/engine/theme/elevations/types.ts
Labels: bug

#63 fix(TextField): Внесены исправления и доработки
  packages/core/src/TextField/BaseTextField.tsx
  packages/core/src/TextField/TextField.tsx
  packages/core/src/TextField/elements/Bottom.tsx
  packages/core/src/TextField/stories/TextField.story.tsx
  packages/core/src/TextField/styles/index.ts
  packages/core/src/TextField/styles/types.ts
Labels: bug, enhancement

#67 feat(borderRadii): Добавлено новое значение `max` с полным скруглением
  packages/core/stories/style/borderRadii.story.tsx
  packages/core/styles/engine/theme/borderRadii/createBorderRadii.ts
  packages/core/styles/engine/theme/borderRadii/types.ts
Labels: enhancement

#65 feat: Добавлен хук **useFloating**
  lerna.json
  packages/core/stories/hooks/useFloating.story.tsx
  packages/core/utils/hooks/index.ts
  packages/core/utils/hooks/useFloating/constants.ts
  packages/core/utils/hooks/useFloating/index.ts
  packages/core/utils/hooks/useFloating/maps.ts
  packages/core/utils/hooks/useFloating/modifiers/flip.ts
  packages/core/utils/hooks/useFloating/modifiers/index.ts
  packages/core/utils/hooks/useFloating/modifiers/offset.ts
  packages/core/utils/hooks/useFloating/modifiers/shift.ts
  packages/core/utils/hooks/useFloating/types.ts
  packages/core/utils/hooks/useFloating/useFloating.ts
  packages/core/utils/hooks/useFloating/utils/calcOverflow/calcOverflow.ts
  packages/core/utils/hooks/useFloating/utils/calcOverflow/index.ts
  packages/core/utils/hooks/useFloating/utils/calcOverflow/types.ts
  packages/core/utils/hooks/useFloating/utils/dom/contains.ts
  packages/core/utils/hooks/useFloating/utils/dom/getBoundingClientRect.ts
  packages/core/utils/hooks/useFloating/utils/dom/getClippingRect.ts
  packages/core/utils/hooks/useFloating/utils/dom/getComputedStyle.ts
  packages/core/utils/hooks/useFloating/utils/dom/getDocumentElement.ts
  packages/core/utils/hooks/useFloating/utils/dom/getDocumentRect.ts
  packages/core/utils/hooks/useFloating/utils/dom/getNearestOverflowParent.ts
  packages/core/utils/hooks/useFloating/utils/dom/getNodeName.ts
  packages/core/utils/hooks/useFloating/utils/dom/getNodeScroll.ts
  packages/core/utils/hooks/useFloating/utils/dom/getOffsetParent.ts
  packages/core/utils/hooks/useFloating/utils/dom/getOverflowParents.ts
  packages/core/utils/hooks/useFloating/utils/dom/getParentNode.ts
  packages/core/utils/hooks/useFloating/utils/dom/getRect.ts
  packages/core/utils/hooks/useFloating/utils/dom/getUAString.ts
  packages/core/utils/hooks/useFloating/utils/dom/getViewportRect.ts
  packages/core/utils/hooks/useFloating/utils/dom/getWindow.ts
  packages/core/utils/hooks/useFloating/utils/dom/getWindowScrollBarX.ts
  packages/core/utils/hooks/useFloating/utils/dom/index.ts
  packages/core/utils/hooks/useFloating/utils/dom/is/index.ts
  packages/core/utils/hooks/useFloating/utils/dom/is/isContainingBlock.ts
  packages/core/utils/hooks/useFloating/utils/dom/is/isElement.ts
  packages/core/utils/hooks/useFloating/utils/dom/is/isHTMLElement.ts
  packages/core/utils/hooks/useFloating/utils/dom/is/isNode.ts
  packages/core/utils/hooks/useFloating/utils/dom/is/isOverflowElement.ts
  packages/core/utils/hooks/useFloating/utils/dom/is/isShadowRoot.ts
  packages/core/utils/hooks/useFloating/utils/dom/is/isTableElement.ts
  packages/core/utils/hooks/useFloating/utils/dom/is/isWindow.ts
  packages/core/utils/hooks/useFloating/utils/dom/isLayoutViewport.ts
  packages/core/utils/hooks/useFloating/utils/dom/offsetParentRelativeRectToViewportRelativeRect.ts
  packages/core/utils/hooks/useFloating/utils/dom/rectToClientRect.ts
  packages/core/utils/hooks/useFloating/utils/dom/types.ts
  packages/core/utils/hooks/useFloating/utils/getFloatingPosition/applyModifiers.ts
  packages/core/utils/hooks/useFloating/utils/getFloatingPosition/changePlacement.ts
  packages/core/utils/hooks/useFloating/utils/getFloatingPosition/getFloatingAdditionalCoords.ts
  packages/core/utils/hooks/useFloating/utils/getFloatingPosition/getFloatingContext.ts
  packages/core/utils/hooks/useFloating/utils/getFloatingPosition/getFloatingCoords.ts
  packages/core/utils/hooks/useFloating/utils/getFloatingPosition/getFloatingMainCoords.ts
  packages/core/utils/hooks/useFloating/utils/getFloatingPosition/getFloatingPosition.ts
  packages/core/utils/hooks/useFloating/utils/getFloatingPosition/index.ts
  packages/core/utils/hooks/useFloating/utils/getOffsetMap.ts
  packages/core/utils/hooks/useFloating/utils/getOffsetMapFromTuple.ts
  packages/core/utils/hooks/useFloating/utils/index.ts
  packages/core/utils/hooks/useFloating/utils/isPosition.ts
  packages/core/utils/index.ts
Labels: enhancement
