Repository quarx-ui/quarx, pull requests merged in 2023-06, with the labels that each got.

#233 refactor: Изменен хук useBooleanState
  packages/core/src/main/Accordion/Accordion.tsx
  packages/core/src/main/Dropdown/DropdownItem/DropdownItem.tsx
  packages/core/src/main/Dropdown/DropdownItem/storybook/ellipsis/index.tsx
  packages/core/src/main/Dropdown/DropdownItem/storybook/sandbox/index.tsx
  packages/core/src/main/Dropdown/DropdownItemsGroup/storybook/template.tsx
  packages/core/src/main/Dropdown/storybook/customization/index.tsx
  packages/core/src/main/Dropdown/storybook/sandbox/index.tsx
  packages/core/src/main/Dropdown/storybook/sizes/index.tsx
  packages/core/src/main/Dropdown/storybook/template.tsx
  packages/core/src/main/Selections/Selection/Selection.tsx
  packages/core/src/main/Selections/Selection/storybook/adornment/index.tsx
  packages/core/src/main/Selections/Selection/storybook/booleanParams/index.tsx
  packages/core/src/main/Selections/Selection/storybook/colors/index.tsx
  packages/core/src/main/Selections/Selection/storybook/sandbox/index.tsx
  packages/core/src/main/Selections/Selection/storybook/sizes/index.tsx
  packages/core/src/main/Selections/Selection/storybook/types/index.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionTree/SelectionTreeNode/SelectionTreeNode.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionTree/storybook/StoryUtilButton.tsx
  packages/core/src/system/Popup/storybook/sandbox/index.tsx
  packages/core/utils/hooks/useBooleanState/useBooleanState.ts
  packages/core/utils/hooks/useTimer/useTimer.ts
Labels: refactor

#239 feature(ClickAwayLister): Добавлена возможность игнорирования элементов
  packages/core/src/system/ClickAwayListener/ClickAwayListener.tsx
  packages/core/src/system/ClickAwayListener/storybook/ClickAwayListener.story.tsx
  packages/core/src/system/ClickAwayListener/storybook/sandbox/index.tsx
  packages/core/src/system/ClickAwayListener/types.ts
  packages/core/src/system/Popup/Popup.tsx
  packages/core/src/system/Popup/types.ts
Labels: enhancement

#240 fix(palette): Исправлено переопределение цветов при создании темы
  packages/core/src/main/Accordion/Accordion.tsx
  packages/core/src/main/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
  packages/core/src/main/Accordion/styles/index.ts
  packages/core/styles/engine/theme/palette/createPalette.ts
  packages/core/styles/engine/theme/palette/getDarkPalette.ts
  packages/core/styles/engine/theme/palette/getLightPalette.ts
  packages/core/styles/engine/theme/palette/mergeObjectProps.ts
Labels: bug

#242 tech(Dropdown): Расширена стилизация DropdownItem.
  packages/core/src/main/Dropdown/DropdownItem/DropdownItem.tsx
  packages/core/src/main/Dropdown/DropdownItem/__tests__/__snapshots__/DropdownItem.test.tsx.snap
  packages/core/src/main/Dropdown/DropdownItem/styles/types.ts
  packages/core/src/main/Dropdown/DropdownItem/types.ts
  packages/core/src/main/Dropdown/DropdownItemsGroup/__tests__/__snapshots__/DropdownItemsGroup.test.tsx.snap
Labels: enhancement

#244 fix(Stack): Исправлен конфликт css-переменных для дочерних элементов
  packages/core/src/main/Dropdown/DropdownItemsGroup/__tests__/__snapshots__/DropdownItemsGroup.test.tsx.snap
  packages/core/src/system/Stack/Stack.tsx
  packages/core/src/system/Stack/__tests__/Stack.test.tsx
  packages/core/src/system/Stack/__tests__/__snapshots__/Stack.test.tsx.snap
  packages/core/src/system/Stack/styles/index.ts
  packages/core/src/system/Stack/styles/vars.ts
  packages/core/src/system/Stack/types.ts
Labels: bug

#247 feat(theme): В тему добавлена базовая типографика
  .gitignore
  packages/core/stories/style/typography.story.tsx
  packages/core/styles/engine/theme/createTheme/createTheme.ts
  packages/core/styles/engine/theme/createTheme/types.ts
  packages/core/styles/engine/theme/index.ts
  packages/core/styles/engine/theme/typography/baseTypography/baseTypography.ts
  packages/core/styles/engine/theme/typography/baseTypography/constants.ts
  packages/core/styles/engine/theme/typography/baseTypography/index.ts
  packages/core/styles/engine/theme/typography/baseTypography/types.ts
  packages/core/styles/engine/theme/typography/constants.ts
  packages/core/styles/engine/theme/typography/helpers/createGetTypographyVariant.ts
  packages/core/styles/engine/theme/typography/helpers/createPxToRem.ts
  packages/core/styles/engine/theme/typography/helpers/index.ts
  packages/core/styles/engine/theme/typography/index.ts
  packages/core/styles/engine/theme/typography/map.ts
  packages/core/styles/engine/theme/typography/types.ts
  packages/core/styles/engine/theme/typography/typography.ts
  packages/core/styles/engine/utils/deepMerge/deepMerge.js
  packages/core/styles/typography/typography.ts
Labels: enhancement
