Repository quarx-ui/quarx, pull requests merged in 2023-01, with the labels that each got.

#156 docs: Расширены Code Conventions
  md/conventions/code.md
Labels: documentation

#158 refactor: Увеличено быстродействие проверки типов константных объектов
  packages/core/utils/object/valuesAsKeys/index.ts
Labels: enhancement

#162 tech(cli new): Удален неиспользуемый импорт
  scripts/cli/src/componentLayouts/root.ts
Labels: enhancement

#168 feat(palette)!: Цвета фокуса `dark` и `light` в палитре заменены на `main` и `inverse`
  packages/core/src/main/Button/BaseButton/styles/index.ts
  packages/core/src/main/Checkbox/styles/index.ts
  packages/core/src/main/Chips/styles/index.ts
  packages/core/src/main/Link/styles/index.ts
  packages/core/src/main/RadioButton/styles/index.ts
  packages/core/src/main/Selections/Selection/styles/index.ts
  packages/core/src/main/Switcher/__tests__/__snapshots__/Switcher.test.tsx.snap
  packages/core/src/main/Switcher/styles/index.ts
  packages/core/src/main/Tabs/TabsContained/TabItemContained/styles/index.ts
  packages/core/src/main/Tabs/TabsSegmented/TabItemSegmented/styles/index.ts
  packages/core/stories/style/colors.story.tsx
  packages/core/styles/engine/theme/palette/getDarkPalette.ts
  packages/core/styles/engine/theme/palette/getLightPalette.ts
  packages/core/styles/engine/theme/palette/types.ts
  packages/icons/storybook/Icons.story.tsx
Labels: enhancement

#165 refactor(cli:new): Исправлены баги, рефакторинг структуры
  scripts/cli/new/index.ts
  scripts/cli/new/src/command.ts
  scripts/cli/new/src/creature/constants.ts
  scripts/cli/new/src/creature/index.ts
  scripts/cli/new/src/creature/registrations/core.ts
  scripts/cli/new/src/creature/registrations/index.ts
  scripts/cli/new/src/creature/registrations/utils.ts
  scripts/cli/new/src/creature/structures/core/index.ts
  scripts/cli/new/src/creature/structures/core/layouts/index.ts
  scripts/cli/new/src/creature/structures/core/layouts/root.ts
  scripts/cli/new/src/creature/structures/core/layouts/storybook.ts
  scripts/cli/new/src/creature/structures/core/layouts/styles.ts
  scripts/cli/new/src/creature/structures/core/layouts/tests.ts
  scripts/cli/new/src/creature/structures/e2e/index.ts
  scripts/cli/new/src/creature/structures/e2e/layouts/index.ts
  scripts/cli/new/src/creature/structures/e2e/layouts/tests.ts
  scripts/cli/new/src/creature/structures/index.ts
  scripts/cli/new/src/creature/structures/types.ts
  scripts/cli/new/src/creature/structures/utils.ts
  scripts/cli/new/src/creature/types.ts
  scripts/cli/new/src/creature/utils.ts
  scripts/cli/new/src/prompt.ts
  scripts/cli/new/src/types.ts
  scripts/cli/src/componentLayouts/utils.ts
Labels: research

#164 feat: Добавлен системный компонент **Stack**
  packages/core/src/system/Stack/Stack.tsx
  packages/core/src/system/Stack/__tests__/Stack.test.tsx
  packages/core/src/system/Stack/__tests__/__snapshots__/Stack.test.tsx.snap
  packages/core/src/system/Stack/index.ts
  packages/core/src/system/Stack/stories/Stack.story.tsx
  packages/core/src/system/Stack/styles/constants.ts
  packages/core/src/system/Stack/styles/index.ts
  packages/core/src/system/Stack/styles/maps.ts
  packages/core/src/system/Stack/styles/types.ts
  packages/core/src/system/Stack/styles/vars.ts
  packages/core/src/system/Stack/types.ts
  packages/core/src/system/index.ts
  packages/core/styles/engine/theme/createTheme/types.ts
  packages/core/utils/addCssToElement.ts
  packages/core/utils/index.ts
Labels: enhancement

#166 feat: Добавлен компонент **Popup**
  packages/core/package.json
  packages/core/polyfills.ts
  packages/core/src/main/Selections/Selection/stories/Selection.story.tsx
  packages/core/src/main/Selections/SelectionGroup/stories/SelectionGroup.story.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionList/stories/SelectionList.story.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionTree/stories/SelectionTree.story.tsx
  packages/core/src/system/Popup/Popup.tsx
  packages/core/src/system/Popup/__tests__/Popup.test.tsx
  packages/core/src/system/Popup/__tests__/__snapshots__/Popup.test.tsx.snap
  packages/core/src/system/Popup/index.ts
  packages/core/src/system/Popup/stories/Popup.story.tsx
  packages/core/src/system/Popup/styles/index.ts
  packages/core/src/system/Popup/styles/types.ts
  packages/core/src/system/Popup/styles/vars.ts
  packages/core/src/system/Popup/types.ts
  packages/core/src/system/Portal/types.ts
  packages/core/src/system/index.ts
  packages/core/storybook/components/StoryDarkerContainer.tsx
  packages/core/storybook/components/index.ts
  packages/core/styles/engine/theme/createTheme/types.ts
  packages/core/utils/hooks/useFloating/types.ts
  packages/core/utils/hooks/useFloating/useFloating.ts
  packages/core/utils/hooks/useFloating/utils/calcOverflow/types.ts
  packages/core/utils/hooks/useFloating/utils/computeElementRect.ts
  packages/core/utils/hooks/useFloating/utils/createParentsList.ts
  packages/core/utils/hooks/useFloating/utils/dom/getOverflowParents.ts
  packages/core/utils/hooks/useFloating/utils/index.ts
  packages/core/utils/polyfills/index.ts
  yarn.lock
Labels: enhancement

#172 feat(Stack): Добавлена возможность заменить корневой тег на кастомный
  packages/core/custom.d.ts
  packages/core/src/system/Stack/Stack.tsx
  packages/core/src/system/Stack/__tests__/Stack.test.tsx
  packages/core/src/system/Stack/__tests__/__snapshots__/Stack.test.tsx.snap
  packages/core/src/system/Stack/stories/CustomComponent/description.md
  packages/core/src/system/Stack/stories/CustomComponent/index.tsx
  packages/core/src/system/Stack/stories/DirectionAndOrder/description.md
  packages/core/src/system/Stack/stories/DirectionAndOrder/index.tsx
  packages/core/src/system/Stack/stories/Stack.story.tsx
  packages/core/src/system/Stack/stories/WithDivider/description.md
  packages/core/src/system/Stack/stories/WithDivider/index.tsx
  packages/core/src/system/Stack/stories/defaultArgs.tsx
  packages/core/src/system/Stack/styles/constants.ts
  packages/core/src/system/Stack/styles/maps.ts
  packages/core/src/system/Stack/styles/types.ts
  packages/core/src/system/Stack/types.ts
  packages/core/storybook/DisplayVariants/DisplayVariants.tsx
Labels: enhancement

#180 feature(ClickableElements): Убран синий/серый оттенок при нажатии по …
  packages/core/src/main/Button/BaseButton/styles/index.ts
  packages/core/src/main/Button/__tests__/__snapshots__/Button.test.tsx.snap
  packages/core/src/main/Checkbox/__tests__/__snapshots__/Checkbox.test.tsx.snap
  packages/core/src/main/Checkbox/styles/index.ts
  packages/core/src/main/Chips/__tests__/__snapshots__/Chips.test.tsx.snap
  packages/core/src/main/Chips/styles/index.ts
  packages/core/src/main/Link/__tests__/__snapshots__/Link.test.tsx.snap
  packages/core/src/main/Link/styles/index.ts
  packages/core/src/main/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  packages/core/src/main/RadioButton/__tests__/__snapshots__/RadioButton.test.tsx.snap
  packages/core/src/main/RadioButton/styles/index.ts
  packages/core/src/main/Selections/Selection/__tests__/__snapshots__/Selection.test.tsx.snap
  packages/core/src/main/Selections/Selection/styles/index.ts
  packages/core/src/main/Selections/SelectionRegistries/SelectionList/__tests__/__snapshots__/SelectionList.test.tsx.snap
  packages/core/src/main/Selections/SelectionRegistries/SelectionTree/__tests__/__snapshots__/SelectionTree.test.tsx.snap
  packages/core/src/main/SidePage/__tests__/__snapshots__/SidePage.test.tsx.snap
Labels: enhancement

#176 feature(scripts:new): Изменена структура storybook
  package.json
  scripts/cli/new/src/creature/structures/core/index.ts
  scripts/cli/new/src/creature/structures/core/layouts/root.ts
  scripts/cli/new/src/creature/structures/core/layouts/storybook.ts
  scripts/cli/new/src/creature/structures/core/layouts/styles.ts
  scripts/cli/new/src/creature/structures/core/layouts/tests.ts
Labels: enhancement
