Repository quarx-ui/quarx, pull requests merged in 2023-05, with the labels that each got.

#212 test: Ремаунт компонента при изменениях
  e2e/render-utils/withPropsContext.tsx
  e2e/src/main/Accordion/tests/Accordion.test.pw.ts
  e2e/src/main/Accordion/tests/Accordion.test.pw.ts-snapshots/initialOpen/false/Accordion-chromium-darwin.jpeg
  e2e/src/main/Accordion/tests/Accordion.test.pw.ts-snapshots/initialOpen/false/Accordion-firefox-darwin.jpeg
  e2e/src/main/Accordion/tests/Accordion.test.pw.ts-snapshots/initialOpen/false/Accordion-webkit-darwin.jpeg
  e2e/src/main/Accordion/tests/Accordion.test.pw.ts-snapshots/initialOpen/true/Accordion-chromium-darwin.jpeg
  e2e/src/main/Accordion/tests/Accordion.test.pw.ts-snapshots/initialOpen/true/Accordion-firefox-darwin.jpeg
  e2e/src/main/Accordion/tests/Accordion.test.pw.ts-snapshots/initialOpen/true/Accordion-webkit-darwin.jpeg
Labels: test

#213 fix: Introduction story. Установка
  README.md
  packages/core/README.md
Labels: bug

#217 tech: Исправлены ошибки Liquid Syntax для сборки pages
  packages/core/stories/manuals/Customization/description.md
Labels: documentation

#218 fix: Модальное окно.Замена свойства body на children
  packages/core/src/main/Modal/Modal.tsx
  packages/core/src/main/Modal/storybook/Modal.story.tsx
  packages/core/src/main/Modal/storybook/secondModal/index.tsx
  packages/core/src/main/Modal/types.ts
Labels: research

#220 docs(Selections): Производительность storybook
  packages/core/src/main/Selections/Selection/storybook/booleanParams/index.tsx
  packages/core/src/main/Selections/SelectionGroup/storybook/colors/index.tsx
  packages/core/src/main/Selections/SelectionGroup/storybook/sizes/index.tsx
  packages/core/src/main/Selections/SelectionGroup/storybook/types/index.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionList/SelectionList.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionList/storybook/colors/index.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionList/storybook/sizes/index.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionList/storybook/types/index.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionTree/storybook/colors/index.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionTree/storybook/sizes/index.tsx
  packages/core/src/main/Selections/SelectionRegistries/SelectionTree/storybook/types/index.tsx
  packages/core/storybook/components/Column.tsx
  packages/core/storybook/components/Row.tsx
  packages/core/storybook/components/Title.tsx
  packages/core/storybook/components/index.ts
Labels: bug

#223 fix: Исправлена типизация сборки **@core**
  packages/core/tsconfig.json
Labels: bug

#229 fix(Stack): Ошибка при рендере детей по условию
  packages/core/src/system/Stack/Stack.tsx
  packages/core/src/system/Stack/types.ts
Labels: bug

#232 feat(Stack): Добавлен boolean пропс для Divider
  packages/core/src/main/Dropdown/DropdownItemsGroup/__tests__/__snapshots__/DropdownItemsGroup.test.tsx.snap
  packages/core/src/system/Stack/Stack.tsx
  packages/core/src/system/Stack/__tests__/__snapshots__/Stack.test.tsx.snap
  packages/core/src/system/Stack/helpers.tsx
  packages/core/src/system/Stack/map.ts
  packages/core/src/system/Stack/storybook/Stack.story.tsx
  packages/core/src/system/Stack/storybook/WithDivider/description.md
  packages/core/src/system/Stack/storybook/WithDivider/index.tsx
  packages/core/src/system/Stack/storybook/defaultArgs.tsx
  packages/core/src/system/Stack/styles/index.ts
  packages/core/src/system/Stack/types.ts
Labels: enhancement
